# Generated by Django 4.0.3 on 2022-03-17 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, max_length=700, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='companies/<django.db.models.fields.SlugField>/', verbose_name='Лого')),
                ('contact', models.TextField(max_length=200, verbose_name='Контакты')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('send', 'Отправлено'), ('published', 'Опубликовано'), ('rework', 'На доработку')], default='draft', max_length=15, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Регистратор')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('salary', models.TextField(max_length=150, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес вакансии')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('send', 'Отправлено'), ('published', 'Опубликовано'), ('rework', 'На доработку')], default='draft', max_length=15, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='portal.companycard', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/', verbose_name='Фото')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('contact', models.TextField(max_length=200, verbose_name='Контакты')),
                ('living_city', models.CharField(max_length=50, verbose_name='Город проживания')),
                ('sex', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=15, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
