# Generated by Django 4.0.3 on 2022-03-24 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycard',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=150, verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование вакансии')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('salary', models.CharField(max_length=150, verbose_name='Зарплата')),
                ('employment', models.CharField(max_length=150, verbose_name='Занятость')),
                ('schedule', models.CharField(max_length=150, verbose_name='График работы')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
                ('education', models.TextField(verbose_name='Образование')),
                ('language', models.CharField(max_length=200, verbose_name='Знание языков')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('send', 'Отправлено'), ('published', 'Опубликовано'), ('rework', 'На доработку')], default='draft', max_length=15, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Начало работы')),
                ('finish', models.DateField(default=django.utils.timezone.now, verbose_name='Окончание работы')),
                ('until_now', models.DateField(default=django.utils.timezone.now, verbose_name='До настоящего времени')),
                ('organisation_name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('function', models.TextField(verbose_name='Обязанности')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portal.resume', verbose_name='Резюме')),
            ],
        ),
    ]
