# Generated by Django 4.0.3 on 2022-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарплата'),
        ),
    ]
