# Generated by Django 4.0.3 on 2022-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_companycard_title_alter_vacancy_salary_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='until_now',
            field=models.BooleanField(default=True, verbose_name='До настоящего времени'),
        ),
    ]
