# Generated by Django 4.0.3 on 2022-04-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_resume_comment_vacancy_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('feedback', 'Отклик'), ('suggestion', 'Предложение')], max_length=15, verbose_name='Тип')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('viewed', 'Просмотрено'), ('invite', 'Приглашение'), ('failure', 'Отказ')], default='send', max_length=15, verbose_name='Статус')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='portal.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='resumes',
            field=models.ManyToManyField(related_name='vacancies', through='portal.FeedbackAndSuggestion', to='portal.resume'),
        ),
        migrations.AddField(
            model_name='feedbackandsuggestion',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='portal.vacancy', verbose_name='Вакансия'),
        ),
    ]
