# Generated by Django 3.2.13 on 2022-05-15 02:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm'),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS btree_gin'),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS unaccent'),
    ]
